version: '2'
services:
  web:
    build: web/.
    container_name: bookmark-web
    expose:
     - 5001
    ports:
     - 5001:5001
    volumes:
     - ./web:/web
    working_dir: /web
    depends_on:
     - api
    env_file:
     - web/.env
    command: ""
  api:
    build: api/.
    container_name: bookmark-api
    expose:
     - 5000
    ports:
     - 5000:5000
    volumes:
     - ./api:/api
    working_dir: /api
    depends_on:
     - mongo
    links:
     - mongo
    env_file:
     - api/.env
    command: node server.js
  mongo:
    container_name: bookmark-db
    image: mongo
    expose:
      - "27017"
