version: '2'
services:
  web:
    build: web/.
    container_name: bookmark-web
    expose:
     - 5001
    ports:
     - 5001:5001
    volumes:
     - ./web:/web
    depends_on:
     - api
    env_file:
     - web/.env
    command: ""
  api:
    build: api/.
    container_name: bookmark-api
    expose:
     - 5000
    ports:
     - 5000:5000
    volumes:
     - ./api:/api
    depends_on:
     - mysql
    links:
     - mysql
    env_file:
     - api/.env
    command: ""
  mysql:
    container_name: bookmark-db
    image: mysql:5.7
    expose:
      - "3306"
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
